import { Link } from 'react-router-dom'

/* AUTO-GENERATED by backlink-automation/daily_backlinks.py — do not hand-edit.
   Renders 25 internal backlinks per day, rotated deterministically.
   Sync source: backlink-automation/keywords.json */
const DATA = {"sources": ["/", "/about", "/services", "/portfolio", "/case-studies", "/clients", "/blog", "/testimonials", "/careers", "/contact", "/services/seo", "/services/google-ads", "/services/meta-ads", "/services/social-media-marketing", "/services/content-marketing", "/services/website-development", "/services/branding", "/services/local-seo", "/services/email-marketing", "/blog/seo-trends-2025"], "targets": [{"path": "/services/seo", "anchors": ["SEO services", "SEO experts", "organic ranking services"]}, {"path": "/services/google-ads", "anchors": ["Google Ads experts", "PPC management", "Google Ads optimization"]}, {"path": "/services/meta-ads", "anchors": ["Meta Ads specialists", "Facebook and Instagram ads"]}, {"path": "/services/social-media-marketing", "anchors": ["social media marketing", "social media strategy"]}, {"path": "/services/content-marketing", "anchors": ["content marketing services", "content strategy"]}, {"path": "/services/website-development", "anchors": ["website development", "web development services"]}, {"path": "/services/branding", "anchors": ["branding services", "brand identity design"]}, {"path": "/services/local-seo", "anchors": ["local SEO services", "local SEO for small business"]}, {"path": "/services/email-marketing", "anchors": ["email marketing services", "email campaigns"]}, {"path": "/services/lead-generation", "anchors": ["lead generation services", "lead generation campaigns"]}, {"path": "/blog", "anchors": ["digital marketing blog", "marketing insights"]}, {"path": "/contact", "anchors": ["free consultation", "contact our experts"]}, {"path": "/portfolio", "anchors": ["our portfolio", "recent work"]}, {"path": "/case-studies", "anchors": ["case studies", "client results"]}], "domain": "https://abdigitalsolution.com"} as {
  sources: string[]
  targets: { path: string; anchors: string[] }[]
  domain: string
}
const DAILY_COUNT = 25

type Combo = { source: string; anchor: string; target: string }

function allCombos(): Combo[] {
  const out: Combo[] = []
  for (const src of DATA.sources) {
    for (const t of DATA.targets) {
      if (src === t.path) continue
      for (const anchor of t.anchors) out.push({ source: src, anchor, target: t.path })
    }
  }
  return out
}

export function linksForDay(date = new Date()): Combo[] {
  const combos = allCombos()
  if (!combos.length) return []
  const days = Math.floor(date.getTime() / 86400000)
  const start = (days * DAILY_COUNT) % combos.length
  const out: Combo[] = []
  for (let i = 0; i < Math.min(DAILY_COUNT, combos.length); i++) {
    out.push(combos[(start + i) % combos.length])
  }
  return out
}

export default function AutoInternalLinks() {
  const links = linksForDay()
  if (!links.length) return null
  return (
    <nav aria-label="Related services" style={{ margin: '0', padding: '1.5rem 0', borderTop: '1px solid #eee', fontSize: '0.9rem' }}>
      <strong>Related:</strong>{' '}
      {links.map((l, i) => (
        <span key={`${l.target}-${l.anchor}-${i}`}>
          {i > 0 && ' | '}
          <Link to={l.target} title={l.anchor}>{l.anchor}</Link>
        </span>
      ))}
    </nav>
  )
}
